import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';

export default function Footer({ content }: { content?: any }) {
  const year = new Date().getFullYear();
  return (
    <footer className="overflow-hidden bg-[#171719] px-5 pb-8 pt-20 text-white sm:px-8 sm:pt-28 lg:px-12">
      <div className="mx-auto max-w-[1440px]">
        <div className="grid gap-10 border-b border-white/20 pb-16 lg:grid-cols-[1fr_.55fr] lg:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#c9f44c]">The next good thing starts here</p><h2 className="mt-4 text-[clamp(3.4rem,8vw,8.7rem)] font-semibold leading-[.82] tracking-[-.08em]">Have an ambitious idea?<br /><span className="font-['Playfair_Display'] font-medium italic text-[#9ee6dc]">Let&apos;s make it real.</span></h2></div><div className="lg:pb-2"><p className="max-w-sm text-base leading-relaxed text-white/60">Bring us the hard problem, the unfinished thought, or the idea worth pursuing. We&apos;ll help find the way through it.</p><Link href="/contact" className="group mt-7 inline-flex items-center gap-3 rounded-full bg-[#c9f44c] px-6 py-4 text-xs font-bold uppercase tracking-[.15em] text-[#171719] transition-transform hover:-translate-y-1">Start a conversation <ArrowUpRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></Link></div></div>
        <div className="grid gap-10 py-12 sm:grid-cols-2 lg:grid-cols-[1.2fr_.6fr_.8fr_.8fr]"><div><Link href="/" className="text-3xl font-semibold tracking-[-.09em]">orbit<span className="text-[#9ee6dc]">think</span><span className="ml-1 text-base text-[#ff8066]">✦</span></Link><p className="mt-4 max-w-xs text-sm leading-relaxed text-white/50">A product and engineering studio for useful digital things.</p></div><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/40">Explore</p><div className="mt-4 flex flex-col gap-2 text-sm text-white/70"><Link href="/#services" className="hover:text-[#c9f44c]">Capabilities</Link><Link href="/#work" className="hover:text-[#c9f44c]">Work</Link><Link href="/#process" className="hover:text-[#c9f44c]">Approach</Link></div></div><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/40">Studio</p><div className="mt-4 flex flex-col gap-2 text-sm text-white/70"><Link href="/about" className="hover:text-[#c9f44c]">About</Link><Link href="/portfolio" className="hover:text-[#c9f44c]">Portfolio</Link><Link href="/contact" className="hover:text-[#c9f44c]">Contact</Link></div></div><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/40">Say hello</p><a href={`mailto:${content?.contactEmail || 'contact@orbitthink.com'}`} className="mt-4 block text-sm text-[#9ee6dc] hover:underline">{content?.contactEmail || 'contact@orbitthink.com'}</a><p className="mt-2 text-sm text-white/50">Worldwide, remote by design</p></div></div>
        <div className="flex flex-col justify-between gap-3 border-t border-white/15 pt-6 text-[10px] uppercase tracking-[.12em] text-white/40 sm:flex-row"><span>© {year} OrbitThink. All rights reserved.</span><div className="flex gap-5"><Link href="/contact" className="hover:text-white">Privacy</Link><Link href="/contact" className="hover:text-white">Terms</Link></div></div>
      </div>
    </footer>
  );
}
